### PR TITLE
Improved mapgen

### PR DESCRIPTION
**Pull request by GoodClover**
- The world border now goes to y=+∞,-∞
- The infinite ocean is now made entirely of `solid_water` (no point simulating water out there)
- `solid_water` used for border not below bedrock or above y=0
- Stone generates under a small layer of dirt

TODO:
- [x] Configure generation numbers via config

### CODE REVIEW

**Comment by GoodClover** [comment]
@rollerozxa It appears the player spawns in the ground by one block, y=0.
Either the mapgen needs to be moved down a block or the player spawn up.
(This is an existing issue, not one with this mapgen.)

**Comment by GoodClover** [comment]
I'm wondering whether bedrock should be generated outside the border (at the same y-level as inside).
Currently it looks a bit weird lighting-wise without it.
image

**Comment by GoodClover** [comment]
'pologies for the git fuckery

**Comment by rollerozxa** [comment]
https://www.classicube.net/server/play/?warned=true

**Comment by GoodClover** [comment]
More explanation than just a link would be nice in future.
I assume you mean you want to re-create that mapgen.

**Pull request closed without merging**
